@startuml classes
skinparam classAttributeIconSize 0

class JsonObject {
  + from_json(json_object: String): JsonObject
  + to_json(): String
}

Class Model {
  - id: UUID 
}

class Pessoa {
  -  cpf: String
  -  nome: String
  -  endereco: String
}

class Palestrante {
  - tema: String
  - credenciais: String
}

class Conferencia {
  - titulo: String
  - ano: Integer
}

class Espectador {
  - instituicao_de_origem: String
  - grau_de_escolaridade: String
}

JsonObject <|- Model
Model <|- Pessoa

Conferencia "1" o-- "n" Pessoa

Pessoa <|-- Espectador
Pessoa <|-- Palestrante

@enduml